### ISSUE TITLE
UnboundLocalError: local variable 'font_loc' referenced before assignment

### ISSUE THREAD

**Issue by RohitKeshari** [lewis-morris/mapextrackt#3]
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-297-3de271c35129> in <module>
----> 1 fe.display_from_map(layer_no=2, cell_no=4)

~/SageMaker/speedlimit/mapextrackt/MapExtrackt/extractor.py in display_from_map(self, layer_no, cell_no, out_type, colourize, outsize, border, picture_in_picture, write_text)
    194         if self.write_text.lower() != "none":
    195             subtext = ""
--> 196             img = self.__write_text_(img, layer_no, cell_no)
    197 
    198         if self.out_type.lower() == "pil":

~/SageMaker/speedlimit/mapextrackt/MapExtrackt/extractor.py in __write_text_(self, img, layer_no, cell_no, flip)
    242         if flip:
    243             text, subtext = subtext, text
--> 244         img = draw_text(img, text, subtext)
    245 
    246         return img

~/SageMaker/speedlimit/mapextrackt/MapExtrackt/functions.py in draw_text(img, text, subtext)
    194 
    195 
--> 196     font = ImageFont.truetype(font_loc, size)
    197     smaller_font = ImageFont.truetype(font_loc, smaller_size)
    198 

UnboundLocalError: local variable 'font_loc' referenced before assignment

**Comment by lewis-morris** [comment]
What operating system are you using? And which version of python?

**Comment by lewis-morris** [comment]
I realise you are using amazon sagemaker. 

I've located the directory and installed fonts used by amazon, updated the code, pushed a new package to PYPI.

Make sure you use  !pip install mapextrackt==0.4.8.6 to get the latest version.

All should be groovy from here on out.

**Comment by lewis-morris** [comment]
If you enjoy MapExtrackt please give it a star for me :)
